spring:
  application:
    name: ezim
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 15MB

  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: emmmm000
      jedis:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 10
          min-idle: 0
      connect-timeout: 2000

server:
  servlet:
    context-path: /api
  port: 9090

ws:
  port: 9091

mybatis:
  type-aliases-package: org.chc.ezim.entity.model,org.chc.ezim.entity.dto
  configuration:
    map-underscore-to-camel-case: true
