spring:
  application:
    name: ezim
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 15MB

server:
  servlet:
    context-path: /api
  port: 8080

ws:
  port: 8081

mybatis:
  type-aliases-package: org.chc.ezim.entity.model,org.chc.ezim.entity.dto
  configuration:
    map-underscore-to-camel-case: true
